import type { AnalysisReport, MultiAnalysisSummary } from "../types/index.js";
import { formatFileSize } from "../utils/file.js";
import { scopeIcon, scopeLabel } from "../utils/detectTarget.js";
import { getScoreStatus } from "../utils/scoring.js";

const C = {
  bg: "#1A1A2E",
  bgCard: "#16213E",
  bgHover: "#1A2744",
  text: "#E2DCC8",
  textSecondary: "#8A8FA0",
  border: "#2A2A4A",
  primary: "#D4A574",
  secondary: "#7AB8A0",
  accent: "#D4756B",
  success: "#7ECBA0",
  warning: "#E8C87A",
  error: "#D4756B",
  info: "#8AB8D4",
  muted: "#6B7280",
  gradient1: "#D4A574",
  gradient2: "#7AB8A0",
};

export class HtmlReporter {
  render(report: AnalysisReport): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>repoinsight Report — ${this.esc(report.projectName)}</title>
<style>${this.sharedStyles()}</style>
</head>
<body>
<div class="container">
  <div class="brand">
    <div class="brand-logo">R</div>
    <div>
      <h1>${this.esc(report.projectName)}</h1>
      <div class="sub">${this.esc(report.projectPath)}</div>
      <div class="sub" style="margin-top:4px;font-size:.85rem">${scopeIcon(report.scope.type)} ${scopeLabel(report.scope.type)} — ${this.esc(report.scope.targetPath)}</div>
      <div class="sub" style="margin-top:6px;font-size:.75rem">${report.analyzedAt} · ${report.duration}ms</div>
    </div>
  </div>

  <div class="score-wrap">
    <div class="score-ring sc-${this.scoreClass(report.score)}">${report.score}</div>
    <div class="score-label">overall health</div>
  </div>

  <div class="grid">
    <div class="card"><div class="val">${report.summary.totalFiles}</div><div class="lbl">Files</div></div>
    <div class="card"><div class="val">${report.summary.totalFolders}</div><div class="lbl">Folders</div></div>
    <div class="card"><div class="val">${formatFileSize(report.summary.totalSize)}</div><div class="lbl">Size</div></div>
    <div class="card"><div class="val">${report.summary.languages}</div><div class="lbl">Languages</div></div>
    <div class="card"><div class="val">${report.summary.commits}</div><div class="lbl">Commits</div></div>
    <div class="card"><div class="val">${report.summary.contributors}</div><div class="lbl">Contributors</div></div>
  </div>

  ${this.techSection(report.technologies)}

  <div class="sec">
    <h2>Category Scores</h2>
    <div class="cat-grid">${report.categoryScores.map((c) => this.catCard(c)).join("")}</div>
  </div>

  <div class="sec">
    <h2>Languages</h2>
    <table>
      <thead><tr><th>Language</th><th>Files</th><th>Share</th></tr></thead>
      <tbody>${report.languages
        .slice(0, 10)
        .map(
          (l) =>
            `<tr><td>${this.esc(l.language)}</td><td>${l.files}</td><td>${l.percentage}%</td></tr>`,
        )
        .join("")}</tbody>
    </table>
  </div>

  ${report.gitStats ? this.gitSection(report) : ""}
  ${this.issuesHtml(report)}

  ${
    report.recommendations.length
      ? `
  <div class="sec">
    <h2>Recommendations</h2>
    <ul class="rec-list">${report.recommendations.map((r) => `<li>${this.esc(r)}</li>`).join("")}</ul>
  </div>`
      : ""
  }

  ${
    report.biggestFiles.length
      ? `
  <div class="sec">
    <h2>Biggest Files</h2>
    <table><thead><tr><th>File</th><th>Size</th></tr></thead>
    <tbody>${report.biggestFiles
      .slice(0, 10)
      .map((f) => `<tr><td>${this.esc(f.path)}</td><td>${formatFileSize(f.size)}</td></tr>`)
      .join("")}</tbody></table>
  </div>`
      : ""
  }

  ${
    report.largeAssets.length
      ? `
  <div class="sec">
    <h2>Large Assets</h2>
    <table><thead><tr><th>File</th><th>Size</th><th>Type</th></tr></thead>
    <tbody>${report.largeAssets.map((a) => `<tr><td>${this.esc(a.path)}</td><td>${formatFileSize(a.size)}</td><td>${this.esc(a.type)}</td></tr>`).join("")}</tbody></table>
  </div>`
      : ""
  }

  ${
    report.complexity.filter((c) => c.cyclomaticComplexity > 10).length
      ? `
  <div class="sec">
    <h2>Complex Code</h2>
    <table><thead><tr><th>File</th><th>Lines</th><th>Complexity</th><th>Functions</th></tr></thead>
    <tbody>${report.complexity
      .filter((c) => c.cyclomaticComplexity > 10)
      .map(
        (c) =>
          `<tr><td>${this.esc(c.file)}</td><td>${c.linesOfCode}</td><td>${c.cyclomaticComplexity}</td><td>${c.functionCount}</td></tr>`,
      )
      .join("")}</tbody></table>
  </div>`
      : ""
  }

  <footer>Generated by <strong>repoinsight</strong> — Understand any repository in seconds.</footer>
</div>
</body>
</html>`;
  }

  private catCard(cat: { name: string; percentage: number; status: string }): string {
    const color = this.statColor(cat.status);
    return `<div class="cat-card">
      <h3>${this.cap(cat.name)}</h3>
      <div class="pct" style="color:${color}">${cat.percentage}%</div>
      <div class="bar"><div class="bar-fill" style="width:${cat.percentage}%;background:${color}"></div></div>
      <div><span class="badge" style="background:${color}22;color:${color}">${this.cap(cat.status)}</span></div>
    </div>`;
  }

  private techSection(tech: AnalysisReport["technologies"]): string {
    const items: string[] = [];
    const add = (label: string, vals: string[]) => {
      if (vals.length) {
        items.push(
          `<div class="card"><div class="val" style="font-size:1rem">${vals.join(", ")}</div><div class="lbl">${label}</div></div>`,
        );
      }
    };
    const pm = tech.packageManager
      ? tech.packageManager + (tech.packageManagerVersion ? ` ${tech.packageManagerVersion}` : "")
      : null;
    if (pm) {
      add("Package", [pm]);
    }
    if (tech.monorepo) {
      add("Monorepo", [tech.monorepo]);
    }
    add("Framework", tech.frameworks);
    add("Testing", tech.testFrameworks);
    add("Linter", tech.linters);
    add("Hooks", tech.gitHooks);
    add("CI/CD", tech.ciProviders);
    if (tech.nodeVersion) {
      add("Node", [tech.nodeVersion]);
    }
    if (tech.typescript) {
      add("Lang", ["TypeScript"]);
    }
    const docs: string[] = [];
    if (tech.hasReadme) {
      docs.push("README");
    }
    if (tech.hasLicense) {
      docs.push("LICENSE");
    }
    if (tech.hasSecurity) {
      docs.push("SECURITY");
    }
    if (tech.hasContributing) {
      docs.push("CONTRIBUTING");
    }
    add("Docs", docs);
    return `<div class="sec"><h2>Technologies</h2><div class="grid">${items.join("")}</div></div>`;
  }

  private gitSection(report: AnalysisReport): string {
    const g = report.gitStats!;
    let tmpl = `<div class="sec"><h2>Git Statistics</h2><div class="grid">
      <div class="card"><div class="val">${g.commitCount}</div><div class="lbl">Commits</div></div>
      <div class="card"><div class="val">${g.branchCount}</div><div class="lbl">Branches</div></div>
      <div class="card"><div class="val">${g.contributorCount}</div><div class="lbl">Contributors</div></div>
    </div>`;
    if (g.largestCommits.length) {
      tmpl += `<table style="margin-top:12px"><thead><tr><th>Author</th><th>Message</th><th>Files</th><th>Date</th></tr></thead>
      <tbody>${g.largestCommits
        .slice(0, 5)
        .map(
          (c) =>
            `<tr><td>${this.esc(c.author)}</td><td>${this.esc(c.message.substring(0, 50))}</td><td>${c.filesChanged}</td><td>${this.esc(c.date)}</td></tr>`,
        )
        .join("")}</tbody></table>`;
    }
    return tmpl + `</div>`;
  }

  private issuesHtml(report: AnalysisReport): string {
    const p: string[] = [];
    if (report.hardcodedSecrets.length) {
      p.push(
        `<h3 style="margin-bottom:8px">Secrets <span class="badge" style="background:${C.error}22;color:${C.error}">${report.hardcodedSecrets.length}</span></h3>`,
      );
      for (const s of report.hardcodedSecrets.slice(0, 10)) {
        p.push(
          `<div class="issue issue-crit"><strong>${this.esc(s.file)}:${s.line}</strong> — ${this.esc(s.type)}<br><code>${this.esc(s.context)}</code></div>`,
        );
      }
    }
    if (report.todoComments.length) {
      p.push(
        `<h3 style="margin:16px 0 8px">TODOs <span class="badge" style="background:${C.warning}22;color:${C.warning}">${report.todoComments.length}</span></h3>`,
      );
      for (const t of report.todoComments.slice(0, 20)) {
        p.push(
          `<div class="issue issue-warn"><strong>${this.esc(t.file)}:${t.line}</strong> [${this.esc(t.type)}] ${this.esc(t.text)}</div>`,
        );
      }
    }
    if (report.dependencyIssues.length) {
      p.push(
        `<h3 style="margin:16px 0 8px">Dependencies <span class="badge" style="background:${C.warning}22;color:${C.warning}">${report.dependencyIssues.length}</span></h3>`,
      );
      for (const d of report.dependencyIssues.slice(0, 15)) {
        p.push(
          `<div class="issue ${d.severity === "critical" ? "issue-crit" : "issue-warn"}">${this.esc(d.name)} — ${d.type} (${d.severity})</div>`,
        );
      }
    }
    if (report.circularImports.length) {
      p.push(
        `<h3 style="margin:16px 0 8px">Circular Imports <span class="badge" style="background:${C.error}22;color:${C.error}">${report.circularImports.length}</span></h3>`,
      );
      for (const c of report.circularImports.slice(0, 10)) {
        p.push(
          `<div class="issue issue-crit"><strong>${this.esc(c.file)}</strong> → ${this.esc(c.chain.join(" → "))}</div>`,
        );
      }
    }
    return p.length ? `<div class="sec"><h2>Issues</h2>${p.join("")}</div>` : "";
  }

  private esc(s: string): string {
    return s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }

  private scoreClass(s: number): string {
    return getScoreStatus(s);
  }

  private statColor(s: string): string {
    const m: Record<string, string> = {
      excellent: C.success,
      good: C.secondary,
      fair: C.warning,
      poor: C.accent,
      critical: C.error,
    };
    return m[s] ?? C.muted;
  }

  private cap(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }

  renderMulti(summary: MultiAnalysisSummary): string {
    const grade = (sc: number): string =>
      sc >= 90 ? "A" : sc >= 80 ? "B" : sc >= 65 ? "C" : sc >= 50 ? "D" : "F";

    const gradeColor = (sc: number): string =>
      sc >= 80 ? C.success : sc >= 60 ? C.warning : C.error;

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>repoinsight Multi-Path Report</title>
<style>${this.sharedStyles()}
.multi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; margin-bottom: 24px; }
.result-card { background: ${C.bgCard}; border: 1px solid ${C.border}; border-radius: 10px; padding: 16px; margin-bottom: 12px; }
.result-card:hover { border-color: ${C.primary}44; }
.result-card .path { font-size: .8rem; color: ${C.textSecondary}; margin-top: 4px; }
.result-card .error { color: ${C.error}; }
.project-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; }
.project-card { background: ${C.bgCard}; border: 1px solid ${C.border}; border-radius: 10px; padding: 16px; }
.project-card h3 { font-size: .9rem; color: ${C.primary}; margin-bottom: 8px; }
.project-card .stat { font-size: .8rem; color: ${C.textSecondary}; }
</style>
</head>
<body>
<div class="container">
  <div class="brand">
    <div class="brand-logo">R</div>
    <div>
      <h1>Multi-Path Analysis Report</h1>
      <div class="sub">${summary.totalTargets} target(s) · ${summary.repositories} repositories · ${summary.directories} directories</div>
      <div class="sub" style="margin-top:4px;font-size:.85rem">Total files scanned: ${summary.totalFiles}</div>
    </div>
  </div>

  <div class="score-wrap">
    <div class="score-ring sc-${this.scoreClass(summary.averageScore)}" style="font-size:2rem">
      ${grade(summary.averageScore)}
    </div>
    <div class="score-label">average health score (${summary.averageScore}/100)</div>
  </div>

  <div class="multi-grid">
    <div class="card"><div class="val">${summary.totalTargets}</div><div class="lbl">Targets</div></div>
    <div class="card"><div class="val">${summary.repositories}</div><div class="lbl">Repositories</div></div>
    <div class="card"><div class="val">${summary.directories}</div><div class="lbl">Folders</div></div>
    <div class="card"><div class="val">${summary.files}</div><div class="lbl">Files</div></div>
    <div class="card"><div class="val">${summary.totalFiles}</div><div class="lbl">Total Files Scanned</div></div>
  </div>

  ${
    summary.bestProject
      ? `
  <div class="sec">
    <h2>Best Project</h2>
    <div style="background:${C.bgCard};border:1px solid ${C.success}44;border-radius:10px;padding:16px">
      <div style="font-size:1.2rem;font-weight:700;color:${C.success}">${this.esc(summary.bestProject.name)}</div>
      <div style="font-size:.85rem;color:${C.textSecondary};margin-top:4px">Score: ${summary.bestProject.score}/100</div>
    </div>
  </div>`
      : ""
  }

  ${
    summary.worstProject && summary.worstProject.name !== summary.bestProject?.name
      ? `
  <div class="sec">
    <h2>Needs Attention</h2>
    <div style="background:${C.bgCard};border:1px solid ${C.error}44;border-radius:10px;padding:16px">
      <div style="font-size:1.2rem;font-weight:700;color:${C.error}">${this.esc(summary.worstProject.name)}</div>
      <div style="font-size:.85rem;color:${C.textSecondary};margin-top:4px">Score: ${summary.worstProject.score}/100</div>
    </div>
  </div>`
      : ""
  }

  <div class="sec">
    <h2>Per-Project Results (${summary.results.length})</h2>
    ${summary.results
      .map((r) => {
        const name = r.name ?? r.path.split(/[\\/]/).pop() ?? r.path;
        const icon = r.error ? "✗" : "✓";
        const borderCol = r.error
          ? C.error
          : r.report?.score >= 80
            ? C.success
            : r.report?.score >= 60
              ? C.warning
              : C.error;
        return `<div class="result-card" style="border-left:3px solid ${borderCol}">
        <div><strong>${icon} ${scopeIcon(r.type)} ${this.esc(name)}</strong></div>
        <div class="path">${this.esc(r.path)}</div>
        ${
          r.error
            ? `<div class="error">${this.esc(r.error)}</div>`
            : r.report
              ? `
        <div style="margin-top:8px;display:flex;gap:16px;flex-wrap:wrap">
          <span class="stat"><strong>Score:</strong> <span style="color:${gradeColor(r.report.score)}">${r.report.score}/100</span></span>
          <span class="stat"><strong>Files:</strong> ${r.report.fileCount}</span>
          <span class="stat"><strong>Duration:</strong> ${r.report.duration}ms</span>
          ${
            r.report.languages.length
              ? `<span class="stat"><strong>Languages:</strong> ${r.report.languages
                  .slice(0, 3)
                  .map((l) => l.language)
                  .join(", ")}</span>`
              : ""
          }
        </div>`
              : ""
        }
      </div>`;
      })
      .join("")}
  </div>

  <footer>Generated by <strong>repoinsight</strong> — Multi-path analysis · ${new Date().toISOString()}</footer>
</div>
</body>
</html>`;

    return html;
  }

  private sharedStyles(): string {
    return `
  :root { color-scheme: dark; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, sans-serif;
    background: ${C.bg};
    color: ${C.text};
    line-height: 1.6;
  }
  .container { max-width: 1120px; margin: 0 auto; padding: 32px 24px; }

  .brand {
    display: flex; align-items: center; justify-content: center; gap: 12px;
    padding: 48px 24px 32px;
    border-bottom: 1px solid ${C.border};
    margin-bottom: 32px;
    text-align: center;
  }
  .brand-logo {
    width: 48px; height: 48px;
    background: linear-gradient(135deg, ${C.gradient1}, ${C.gradient2});
    border-radius: 14px;
    display: flex; align-items: center; justify-content: center;
    font-size: 22px; font-weight: 800; color: ${C.bg};
  }
  .brand h1 { font-size: 2.2rem; font-weight: 700; color: ${C.primary}; }
  .brand .sub { color: ${C.textSecondary}; font-size: 0.95rem; margin-top: 4px; }

  .score-wrap { text-align: center; margin-bottom: 32px; }
  .score-ring {
    width: 150px; height: 150px; border-radius: 50%;
    display: inline-flex; align-items: center; justify-content: center;
    font-size: 2.8rem; font-weight: 800;
    border: 5px solid; margin-bottom: 8px;
    transition: transform .2s;
  }
  .score-ring:hover { transform: scale(1.05); }
  .sc-excellent { border-color: ${C.success}; color: ${C.success}; }
  .sc-good { border-color: ${C.secondary}; color: ${C.secondary}; }
  .sc-fair { border-color: ${C.warning}; color: ${C.warning}; }
  .sc-poor { border-color: ${C.accent}; color: ${C.accent}; }
  .sc-critical { border-color: ${C.error}; color: ${C.error}; }
  .score-label { font-size: 0.9rem; color: ${C.textSecondary}; }

  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr)); gap: 12px; margin-bottom: 32px; }
  .card {
    background: ${C.bgCard}; border: 1px solid ${C.border}; border-radius: 10px;
    padding: 18px 12px; text-align: center; transition: border-color .2s;
  }
  .card:hover { border-color: ${C.primary}44; }
  .card .val { font-size: 1.6rem; font-weight: 700; color: ${C.primary}; }
  .card .lbl { font-size: 0.75rem; color: ${C.textSecondary}; text-transform: uppercase; letter-spacing: .6px; margin-top: 4px; }

  .sec { margin-bottom: 32px; }
  .sec h2 {
    font-size: 1.1rem; font-weight: 600; margin-bottom: 16px; padding-bottom: 8px;
    border-bottom: 1px solid ${C.border}; color: ${C.secondary};
    display: flex; align-items: center; gap: 8px;
  }
  .sec h2::before { content: "◆"; font-size: .7rem; color: ${C.primary}; }

  .cat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 12px; }
  .cat-card { background: ${C.bgCard}; border: 1px solid ${C.border}; border-radius: 10px; padding: 16px; }
  .cat-card h3 { font-size: .8rem; text-transform: uppercase; letter-spacing: .5px; color: ${C.textSecondary}; margin-bottom: 6px; }
  .cat-card .pct { font-size: 1.4rem; font-weight: 700; }
  .bar { height: 6px; background: ${C.border}; border-radius: 3px; overflow: hidden; margin: 8px 0; }
  .bar-fill { height: 100%; border-radius: 3px; transition: width .6s ease; }
  .badge { display: inline-block; padding: 1px 8px; border-radius: 10px; font-size: .7rem; font-weight: 600; }

  table { width: 100%; border-collapse: collapse; background: ${C.bgCard}; border: 1px solid ${C.border}; border-radius: 8px; overflow: hidden; }
  th, td { padding: 9px 14px; text-align: left; border-bottom: 1px solid ${C.border}; }
  th { background: ${C.bgHover}; font-size: .75rem; text-transform: uppercase; letter-spacing: .4px; color: ${C.textSecondary}; font-weight: 600; }
  tr:last-child td { border-bottom: none; }
  tr:hover td { background: ${C.bgHover}; }

  .issue { padding: 10px 14px; background: ${C.bgCard}; border: 1px solid ${C.border}; border-left: 3px solid; border-radius: 6px; margin-bottom: 6px; font-size: .9rem; }
  .issue-crit { border-left-color: ${C.error}; }
  .issue-warn { border-left-color: ${C.warning}; }
  .issue code { color: ${C.primary}; font-size: .85rem; }

  .rec-list { list-style: none; }
  .rec-list li { padding: 10px 14px; background: ${C.bgCard}; border: 1px solid ${C.border}; border-radius: 8px; margin-bottom: 6px; }
  .rec-list li::before { content: "◆ "; color: ${C.primary}; }

  footer { text-align: center; padding: 24px; color: ${C.muted}; font-size: .8rem; border-top: 1px solid ${C.border}; margin-top: 32px; }

  @media (max-width: 640px) {
    .container { padding: 16px; }
    .brand h1 { font-size: 1.5rem; }
    .grid { grid-template-columns: repeat(2, 1fr); }
    .cat-grid { grid-template-columns: 1fr; }
  }
`;
  }
}
